services:
  app:
    image: mysociety/regmem_vector_search:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/regmem_vector_search      
    volumes:
      - ./:/workspaces/regmem_vector_search/
    environment:
      - HF_TOKEN=${HF_TOKEN:-xxx}